name: Download blacklists
run-name: Downloading lists
on:
    workflow_dispatch:
    schedule:
        - cron: '22 22 * * *'
jobs:
    update:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: downloading lists
              run: |
                cd ./_downloads
                ./dl_lists.sh
